# Generated by Django 4.2.2 on 2023-07-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderedplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderedplaced',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('madhya pradesh', 'MADHYA PRADESH'), ('gujrat', 'GUJRAT'), ('uttar pradesh', 'UTTAR PRADESH'), ('maharastra', 'MAHARASTRA'), ('ANDMAN & NICOBAR', 'ANDMAN & NICOBAR'), ('AANDHRA PRADESH', 'AANDHRA PRADESH'), ('BIHAR', 'BIHAR'), ('RAJISHTAN', 'RAJISHTAN'), ('DELHI', 'DELHI'), ('GOA', 'GOA'), ('ASSAM', 'ASSAM'), ('ARUNACHAL PRADESH', 'ARUNACHAL PRADESH')], max_length=50),
        ),
    ]
